// Copyright 2024 Ryan Neff (@JellyTitan)
// Copyright 2024 Ross Hadden (@rosshadden)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#undef EE_HANDS

#define ENABLE_COMPILE_KEYCODE
#define CUSTOM_SHIFT_KEYS_NEGMODS (MOD_BIT(KC_LGUI) | MOD_BIT(KC_RGUI))

/* Miryoku */
// #define BILATERAL_COMBINATIONS
// #define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4 /* GUI, Alt, Ctrl, Shift */
// #define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH MOD_MASK_GUI
// #define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 120  /* ms */
// #define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 80   /* ms */
// #define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 3000 /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 160  /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~MOD_MASK_SHIFT)
