// Copyright 2024 Ryan Neff (@JellyTitan)
// Copyright 2024 Ross Hadden (@rosshadden)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 175

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define ENABLE_COMPILE_KEYCODE
#define PERMISSIVE_HOLD

#define ENCODER_DIRECTION_FLIP
#define ENCODER_MAP_ENABLE

#define JOYSTICK_BUTTON_COUNT 12
#define JOYSTICK_AXIS_COUNT 4
#define JOYSTICK_AXIS_RESOLUTION 10

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 11

#define CUSTOM_SHIFT_KEYS_NEGMODS (MOD_BIT(KC_LGUI) | MOD_BIT(KC_RGUI))

/* Miryoku */
// #define BILATERAL_COMBINATIONS
// #define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4 /* GUI, Alt, Ctrl, Shift */
// #define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH MOD_MASK_GUI
// #define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 120  /* ms */
// #define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 80   /* ms */
// #define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 3000 /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 160  /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~MOD_MASK_SHIFT)
